### ISSUE TITLE
Run in Background on Windows

### ISSUE THREAD

**Issue by niceman20k** [wiggin77/mailrelay#12]
Hi there,

is there any way to run the working program in background on Windows? I tried with piping & redirecting to NUL but without success. It keeps having the prompt open.
Might be a simple edit in the source so it won't output to stdout, but i am not into Go. But i can compile it on my own, if anyone has a hint, i would be thankful.

**Comment by wiggin77** [comment]
Hi @niceman20k.   There are multiple ways to turn any Windows executable into a service.  A [quick search](https://www.google.ca/search?q=windows+turn+any+exe+to+a+service&sca_esv=634e2b4d7db2b0af&source=hp&ei=G5TTZaegF7_X0PEP5veU0Ak&iflsig=ANes7DEAAAAAZdOiK_Ki64uZZ5MU2fm1HBpGhWvLfp08&ved=0ahUKEwjnmbv1-reEAxW_KzQIHeY7BZoQ4dUDCA8&uact=5&oq=windows+turn+any+exe+to+a+service&gs_lp=Egdnd3Mtd2l6IiF3aW5kb3dzIHR1cm4gYW55IGV4ZSB0byBhIHNlcnZpY2UyBRAhGJ8FMgUQIRifBTIFECEYnwVIzSxQAFicK3AAeACQAQGYAX-gAeIUqgEEMjkuM7gBA8gBAPgBAcICCxAuGIAEGLEDGIMBwgIREC4YgAQYsQMYgwEYxwEY0QPCAgsQABiABBixAxiDAcICDhAAGIAEGIoFGLEDGIMBwgIFEC4YgATCAgsQLhiDARixAxiABMICCBAuGIAEGLEDwgIOEAAYgAQYsQMYgwEYyQPCAgsQABiABBiKBRiSA8ICDhAuGIAEGIoFGLEDGIMBwgIIEAAYgAQYsQPCAgUQABiABMICDhAuGIAEGLEDGIMBGOUEwgIGEAAYFhgewgIHEAAYgAQYDcICCBAAGIAEGKIEwgILEAAYgAQYigUYhgM&sclient=gws-wiz) provides several options but perhaps the easiest is to [NSSM](https://www.helpmegeek.com/run-applications-as-windows-service/).

**Comment by niceman20k** [comment]
Thank you! This does the trick very well (nssm). Searched of course, installed a service myself, but didn't step over nssm.

**Comment by wiggin77** [comment]
Glad it's working for you.
