### ISSUE TITLE
Windows binary not working

### ISSUE THREAD

**Issue by cybercritic** [wiggin77/mailrelay#9]
Running the windows binary does nothing.

**Comment by wiggin77** [comment]
@cybercritic, I'm not sure what you mean.  Running the exe, even with a correct config, is not going to display anything.  It will simply wait for connections and forward emails.  It's meant to be run as a daemon/service.  

Did you try running with the `-test` flag to test your configuration?  See [here](https://github.com/wiggin77/mailrelay#testing-your-configuration).
